### ISSUE TITLE
Create Subordinate API to connect products with suppliers resource

### ISSUE THREAD

**Issue by liyana-fauzi** [devops-suppliers/suppliers#6] opened 2020-02-26 15:43 UTC
**As a** Supplier Manager
**I need** to associate suppliers with their products and wholesale prices
**So that** I can query products associated with suppliers

**Assumptions:**
We have a RESTful API for the vendor resource
The products development team has an existing Restful API for the products resource

**Acceptance Criteria:**
When the Supplier Manager updates the product information in the product resource
Then the information is can be retrieved using the Query function for the subordinate API

**Comment by sinduja123** [comment] 2020-03-23 13:37
Duplicate of Story 12 'Add model attributes for suppliers'

**Closed as completed** 2020-04-01 13:25 UTC
Labels: duplicate
